server:
    port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ftdm?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver



eureka:
      instance:
        hostname: localhost
      client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

mybatis:
      typeAliasesPackage: com.tony.entity
      mapperLocations: classpath:/com/*/mapper/*.xml
      configLocation: classpath:/mybatis/mybatis-config.xml

