server:
    port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ftdm?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service


eureka:
      instance:
        hostname: localhost
      client:
        serviceUrl:
          registerWithEureka: true
          fetchRegistry: false
          defaultZone: http://localhost:8081/eureka/

mybatis:
      typeAliasesPackage: com.tony.entity
      mapperLocations: classpath:/mapper/*.xml
      configLocation: classpath:/mybatis/mybatis-config.xml

