server:
    port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ftdm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-test


eureka:
      instance:
        hostname: localhost
        instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
      client:
        serviceUrl:
          registerWithEureka: true
          fetchRegistry: false
          defaultZone: http://localhost:8083/eureka/


mybatis:
      typeAliasesPackage: service.model
      mapperLocations: classpath:/mapper/*.xml
      configLocation: classpath:/mybatis/mybatis-config.xml

